# Generated by Django 5.2.7 on 2025-10-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savdo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='order',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
