# Generated by Django 5.2.7 on 2025-10-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savdo', '0002_remove_order_address_remove_order_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_delivering',
            field=models.BooleanField(default=False),
        ),
    ]
