# Generated by Django 5.2.7 on 2025-10-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savdo', '0003_order_is_completed_order_is_delivering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_delivering',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', '🆕 Yangi'), ('preparing', '🍳 Tayyorlanmoqda'), ('delivering', '🚚 Yetkazilmoqda'), ('completed', '✅ Yakunlangan'), ('cancelled', '❌ Bekor qilingan')], default='new', max_length=20),
        ),
    ]
